# Generated by Django 3.2.8 on 2021-10-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
